---
title: "FIFA World Cup 2018 Predictions"
author: Wenyao Sha
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document:
    includes:
        in_header: myheader.html
---

```{r setup, include=FALSE}
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)

# create myheader.html
header_file <- file("myheader.html")
writeLines('<link rel="shortcut icon" href="../images/favicon.png" type="image/x-icon">', header_file)
close(header_file)

# format match results in a print-friendly way
print_match_results <- function(match_results){
  
  match_results %>% mutate(
    away_team_score = away_team_score %>% round(),
    home_team_score = home_team_score %>% round()
  ) %>% 
  mutate(score = paste0(away_team_score," : ", home_team_score)) %>% 
  select(away_team, score, home_team)
}

source("../main/main_fifa.R")
```

<br><br>

All predictions given by:

* Massey's rating method 
* applied on [international football match results](https://www.kaggle.com/martj42/international-football-results-from-1872-to-2017)
* equally weighted over a training window of the past 1/2/4 year(s)

<br>

### Group Stage
<br>
```{r predictions, echo = FALSE}
group_stage_results %>% 
  print_match_results() %>% 
  kable() %>%
  gsub("<thead>.*</thead>", "", .) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = T) %>% 
  group_rows("Group A", 1, 6) %>%
  group_rows("Group B", 7, 12) %>% 
  group_rows("Group C", 13, 18) %>% 
  group_rows("Group D", 19, 24) %>% 
  group_rows("Group E", 25, 30) %>% 
  group_rows("Group F", 31, 36) %>% 
  group_rows("Group G", 37, 42) %>% 
  group_rows("Group H", 43, 48)
```

<br><br>

### Group Standings
<br>
```{r standings, echo = FALSE}
points_by_team %>% 
  ungroup() %>% 
  select(-group) %>% 
  kable() %>%
  gsub("<thead>.*</thead>", "", .) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = T) %>% 
  group_rows("Group A", 1, 4) %>%
  group_rows("Group B", 5, 8) %>% 
  group_rows("Group C", 9, 12) %>% 
  group_rows("Group D", 13, 16) %>% 
  group_rows("Group E", 17, 20) %>% 
  group_rows("Group F", 21, 24) %>% 
  group_rows("Group G", 25, 28) %>% 
  group_rows("Group H", 29, 32) %>% 
  row_spec(1:2 + 4 * rep(0:7, each = 2), bold = T, color = "white", background = "steelblue")
```

<br><br>

### Knockout Stage
<br>
```{r round_of_16, echo = FALSE}
bind_rows(
  round_of_16_results,
  quarter_finals_results,
  semi_finals_results,
  third_place_playoff_results,
  finals_results
) %>% 
  print_match_results() %>% 
  kable() %>%
  gsub("<thead>.*</thead>", "", .) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = T) %>% 
  group_rows("Round of 16", 1, 8) %>%
  group_rows("Quarter-finals", 9, 12) %>% 
  group_rows("Semi-finals", 13, 14) %>% 
  group_rows("Third place playoff", 15, 15) %>% 
  group_rows("Finals", 16, 16)
```

<br><br>
